title:            /var/log/security/kt.log
description:      kt.gy blog
disqus_shortname: ktgyblog
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://kt.gy/blog

# Owner/author information
owner:
  name:           Tamás Koczka
  avatar:         avatar.jpg
  bio:            "Works @ <a href='https://tresorit.com' target='_blank'>Tresorit</a>.<br>Plays @ <a href='https://ctftime.org/team/5347' target='_blank'>SpamAndHex</a>.<br>Does security stuff."
  email:          koczkatamas+ktpe@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        koczkatamas
  #facebook:       koczkatamas
  github:         koczkatamas
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  #google_plus:    +yourid

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  hard_wrap: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
